name: dartboard_analytics_flutter
description: A Flutter library for streaming analytics to Dartboard.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  dartboard_analytics:
    path: ../dartboard_analytics
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.2.2
  meta: ^1.15.0
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  web: ^1.1.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
